# Simple test Makefile for Request class
CXX = g++
CXXFLAGS = -std=c++98 -Wall -Wextra -Werror -I.
TARGET = test_request
SRCDIR = src
OBJDIR = obj

# Source files
SRCS = test_request.cpp $(SRCDIR)/Request.cpp
OBJS = $(OBJDIR)/test_request.o $(OBJDIR)/Request.o

# Create directories if they don't exist
$(shell mkdir -p $(OBJDIR))

# Default target
all: $(TARGET)

# Link the executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

# Compile test file
$(OBJDIR)/test_request.o: test_request.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Compile Request.cpp
$(OBJDIR)/Request.o: $(SRCDIR)/Request.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Run tests
test: $(TARGET)
	./$(TARGET)

# Clean up
clean:
	rm -rf $(OBJDIR) $(TARGET)

# Debug build
debug: CXXFLAGS += -g -DDEBUG
debug: $(TARGET)

.PHONY: all test clean debug
